spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: workerp_auth_service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: public_profile, email
            authorization-grant-type: authorization_code
            client-name: Facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    exchange:
      email: email.exchange
    queue:
      email: email.queue
    routing-key:
      email: email.routing.key

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
# App custom variables
app:
  jwt:
    access:
      secret: ${JWT_ACCESS_SECRET}
      expiration: ${JWT_ACCESS_EXPIRATION}
    refresh:
      secret: ${JWT_REFRESH_SECRET}
      expiration: ${JWT_REFRESH_EXPIRATION}
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
  clientReceiveTokensPath: ${CLIENT_RECEIVE_TOKENS_PATH}
  api-get-way-url: ${API_GET_WAY_URL}


server:
  port: ${PORT}
