server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: auth-service
                  uri: http://localhost:8081
                  predicates:
                      - Path=/auth/**, /oauth2/**, /login/**

                - id: user-service
                  uri: http://localhost:8082
                  predicates:
                      - Path=/api/users/**

                - id: util-service // Includes Upload, Mail, Notification
                  uri: http://localhost:8083
                  predicates:
                      - Path=/api/util/**

                - id: company-app-service
                  uri: http://localhost:8084
                  predicates:
                    - Path=/api/company-app/**

                - id: hr-app-service
                  uri: http://localhost:8085
                  predicates:
                    - Path=/api/hr-app/**
