server:
  port: 8080

app:
  client: http://localhost:3000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /oauth2/**, /login/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: util-service // Includes Upload, Mail, Notification
          uri: http://localhost:8083
          predicates:
            - Path=/api/util/**

        - id: company-app-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/company-app/**

        - id: hr-app-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/hr-app/**
