server:
  port: ${PORT:8082}

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: user-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:workerp_users}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:rootpassword}
      authentication-database: admin # MongoDB uses 'admin' db for
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

app:
  jwt:
    access:
      secret: ${JWT_ACCESS_SECRET}