server:
  port: ${PORT:8082}

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:workerp_users}
      username: ${MONGODB_PASSWORD:root}
      password: ${MONGODB_PASSWORD:rootpassword}
      authentication-database: admin # MongoDB uses 'admin' db for authentication

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
