spring:
  config:
    import: "optional:file:.env[.properties]"
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
app:
  jwt:
    access:
      secret: ${JWT_ACCESS_SECRET}
  api-get-way-url: ${API_GET_WAY_URL}
