spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: util-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    exchange:
      email: email.exchange
    queue:
      email: email.queue
    routing-key:
      email: email.routing.key
# App custom variables
app:
  cloudinary:
    cloud-name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    secret-key: ${CLOUDINARY_API_SECRET}
    folder: ${CLOUDINARY_FOLDER}
  codeUtil:
    timeToLive: 5
server:
  port: ${PORT}
