spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: workerp_common_lib
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
